apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Chart.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      app: {{ .Chart.name }}
  template:
    metadata:
      name: bank-app-pod
      labels:
        app: {{ .Chart.name }}
    containers:
      - name: my-bank-app-pods
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: 80
        imagePullPolicy: {{ Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.resource.limit.cpu }}
            memory: {{ .Values.resource.limit.memory }}
          requests:
            cpu: {{ .Values.resource.request.cpu }}
            memory: {{ .Values.resource.request.memory }}