apiVersion: v1
kind: Service
metadata: 
  name: bank-app-svc
  label:
    app: {{ .Chart.name }}-svc
spec:
   type: {{ .Values.service.type }}      
   selector:
     app: {{ .Chart.name }}
  ports:
    - targetPort: 80
      port: {{ .Values.service.port }}
      protocol: TCP